### ISSUE TITLE
YandexMetricaPush initialization crash

### ISSUE THREAD

**Issue by 3c133ps3d** [yandexmobile/metrica-push-sdk-android#19]
I am using module [sample-using-firebase](https://github.com/yandexmobile/metrica-push-sdk-android/tree/master/sample-using-firebase) from example for testing.

Error stack from logcat:

>     java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yandex/metrica/push/CommandIntentService;
        at com.yandex.metrica.push.impl.f.a(SourceFile:54)
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144)
        at my.example.push.App.onCreate(App.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

>     Caused by: java.lang.ClassNotFoundException: com.yandex.metrica.push.CommandIntentService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yandex.metrica.push.impl.f.a(SourceFile:54) 
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144) 
        at my.example.push.App.onCreate(App.java:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

>     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/AppMetricaPushJobIntentService;
        at com.yandex.metrica.push.impl.f.a(SourceFile:54) 
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144) 
        at my.example.push.App.onCreate(App.java:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

>      Caused by: java.lang.ClassNotFoundException: android.support.v4.app.AppMetricaPushJobIntentService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yandex.metrica.push.impl.f.a(SourceFile:54) 
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144) 
        at my.example.push.App.onCreate(App.java:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

>      Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
        at com.yandex.metrica.push.impl.f.a(SourceFile:54) 
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144) 
        at my.example.push.App.onCreate(App.java:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

>      Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/my.example.push-hihj1AXmRbkF0jproB_2HQ==/base.apk"],nativeLibraryDirectories=[/data/app/my.example.push-hihj1AXmRbkF0jproB_2HQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yandex.metrica.push.impl.f.a(SourceFile:54) 
        at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:144) 
        at my.example.push.App.onCreate(App.java:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by KondratyonokNikita** [comment]
Hello. Thanks for your report. You have to enable Jetifier to make sample work. Just fixed it in https://github.com/yandexmobile/metrica-push-sdk-android/pull/20

**Comment by 3c133ps3d** [comment]
Thx, its woking now.
