### ISSUE TITLE
IllegalArgumentException with com.google.firebase:firebase-iid:20.3.0

### ISSUE THREAD

**Issue by bondarenko-sergey-v** [yandexmobile/metrica-push-sdk-android#24]
1. Metrica.push.PushService uses method getInstance() of Firebase Instance ID
2. When Firebase Instance ID dependency resolves to version 20.3.0, call of getInstance() leads IllegalArgumentException "Please set your project ID. A valid Firebase project ID is required..."
3. At the same time other Firebase services works fine

Stacktrace:
`2020-10-22 02:21:20.800 14174-14236/ru.getpharma.eapteka E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: ru.getpharma.eapteka, PID: 14174
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.3.0:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@20.3.0:54)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.3.0:2)
        at com.yandex.metrica.push.impl.bj.a(SourceFile:54)
        at com.yandex.metrica.push.PushService$a.a(SourceFile:116)
        at com.yandex.metrica.push.CommandIntentService.onHandleWork(SourceFile:39)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) `

**Comment by dzinad** [comment]
Hello. Please, specify AppMetrica Push SDK version that you're using.
