### ISSUE TITLE
Crash my app

### ISSUE THREAD

**Issue by dimmduh** [yandexmobile/metrica-push-sdk-android#4]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;

`FATAL EXCEPTION: main
                                                                  Process: com.offer4app.demo, PID: 2242
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                      at com.yandex.metrica.push.impl.ag.<init>(SourceFile:26)
                                                                      at com.yandex.metrica.push.PushService.onCreate(SourceFile:82)
                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3808)
                                                                      at android.app.ActivityThread.access$2100(ActivityThread.java:222)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-support-annotations-25.1.0_dc2a4416317ab9593a641b4a3e901067dbfbbabf-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-rxjava-1.1.6_c4f9396dd8e9684762e1d983f61716b8f69f7fb6-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-retrofit-2.1.0_2cf0425cdcffe0ed701311acd288fa0f1c772415-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-realm-annotations-2.3.0_37a2c275d1d9979267438135a59a85c91a075f69-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-picasso-2.5.2_c4adeb7c2b92d79c908dcd239f65af7a2eda0c65-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-okio-1.8.0_1049681f13aa5325b659c493b61e4322b2d5b32f-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-okhttp-3.3.1_90d5169a2c23476abc033cbaf2d3900e8986adba-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-logging-interceptor-3.3.1_5e1ba7ecbc6a21d9eef28bbc9fd6a28bc63d8d24-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-io.realm-realm-android-library-2.3.0_73eef478a18df068bda3aa74539138b019ec661a-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-io.realm-android-adapters-1.4.0_66d129c62635f2488af22e04e0aaa043e5f512b6-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-io.reactivex-rxandroid-1.2.1_5f2c015820310bccd02d049e1f2d2cde5c548d61-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-gson-2.7_ae4d47f1fafe9519bc4014fad016a7f92daafb16-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-gson-2.3.1_aecbe4512d471c4066a7dede2b7329852b9374ae-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-glide-3.7.0_72b37ed7006e73706a394ae33e18f09ec25336fe-classes.dex", dex file "/data/data/com.offer4app.demo/files/instant-run/dex/slice-de.hdodenhof-circleimageview-2.1.0_bfeed90b346ebb18309c02db46ac65bd2a92919a-classes.dex", dex file "/data/data/`

**Comment by dimmduh** [comment]
ohh, fogot to add dependency
compile 'com.google.android.gms:play-services:10.0.1'
