### ISSUE TITLE
DeadObjectException

### ISSUE THREAD

**Issue by OJIer3** [yandexmobile/metrica-push-sdk-android#8]
v0.6.1, specific for OnePlus One, android 6.0.1

Fatal Exception: java.lang.RuntimeException: Unable to create application: java.lang.RuntimeException: Package manager has died
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4754)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:135)
       at com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
       at com.yandex.metrica.push.impl.ah.a(SourceFile:1036)
       at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:1077)
Caused by android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2235)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:130)
       at com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
       at com.yandex.metrica.push.impl.ah.a(SourceFile:1036)
       at com.yandex.metrica.push.YandexMetricaPush.init(SourceFile:1077)

**Comment by alexklints** [comment]
Hello. It's device specific problem with package manager. We'll add fix to avoid crash in this case in future releases.

**Comment by OJIer3** [comment]
Thx

**Comment by NesterovichAlexey** [comment]
In version 1.0.0 this problem has been fixed.

**Comment by cyph3rcod3r** [comment]
Whats the fix for this exception! should we catch it and leave or what?

**Comment by EddyMM** [comment]
@NesterovichAlexey , what was the fix for this issue?

**Comment by NesterovichAlexey** [comment]
You don't need to fix anything. In the SDK, all calls to the Package Manager were wrapped in a try/catch block.

Is this still a issue?
